title: "Elfateh Sandbox"
email: ""
description: "A simple personal blog to share my thoughts."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elfateh4.github.io"
permalink: /posts/:title/

# SEO defaults
social_image: "/assets/images/social.png" # change to your preferred default social image (absolute or site-relative)
twitter_username: "elfateh_4" 
markdown: kramdown
collections:
  pages:
    output: true
    permalink: /:path/

# Umami Analytics configuration
umami:
  script_url: "https://umami.gate.3launchpad.com/script.js"
  website_id: "39188739-82bb-485a-b32d-320866ae327b"
